import javax.swing.JOptionPane;
import java.time.*;
import java.util.Calendar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdullahatif
 */
public class CreateApplicationGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreenGUI.class.getName());

    /**
     * Creates new form HomeScreenGUI
     */
    User currentUser;
    public CreateApplicationGUI() {
        initComponents();
        JOptionPane.showMessageDialog(this, "An Error Occured", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    public CreateApplicationGUI(User loggedInUser) {
        initComponents();
        currentUser = loggedInUser;
        for (University unis : currentUser.getTotalUniversitiesApplied()) {
            slbxUniversities.addItem(unis.getUniversityName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainInterface = new components.RoundedPanel();
        lblProgramName = new javax.swing.JLabel();
        txfProgramName = new javax.swing.JTextField();
        cbxSuppApp = new javax.swing.JCheckBox();
        calSuppApp = new com.toedter.calendar.JCalendar();
        lblSuppApp = new javax.swing.JLabel();
        calInterview = new com.toedter.calendar.JCalendar();
        lblInterview = new javax.swing.JLabel();
        cbxInterview = new javax.swing.JCheckBox();
        lblUniversityName = new javax.swing.JLabel();
        slbxUniversities = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnAddUni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(244, 243, 240));

        lblName.setBackground(new java.awt.Color(244, 243, 240));
        lblName.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(57, 62, 65));
        lblName.setText("GUAC");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBackground.setBackground(new java.awt.Color(57, 62, 65));

        pnlFooter.setBackground(new java.awt.Color(244, 243, 240));

        jLabel2.setBackground(new java.awt.Color(244, 243, 240));
        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 62, 65));
        jLabel2.setText("@ 2026 Global University Application Centre");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnlMainInterface.setBackground(new java.awt.Color(244, 243, 240));
        pnlMainInterface.setMinimumSize(new java.awt.Dimension(713, 755));

        lblProgramName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblProgramName.setForeground(new java.awt.Color(57, 62, 65));
        lblProgramName.setText("Program Name");

        txfProgramName.setBackground(new java.awt.Color(244, 243, 240));
        txfProgramName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N

        cbxSuppApp.setBackground(new java.awt.Color(244, 243, 240));
        cbxSuppApp.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 16)); // NOI18N
        cbxSuppApp.setForeground(new java.awt.Color(57, 62, 65));
        cbxSuppApp.setText("Supplimentary Application");
        cbxSuppApp.addActionListener(this::cbxSuppAppActionPerformed);

        calSuppApp.setWeekOfYearVisible(false);

        lblSuppApp.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 16)); // NOI18N
        lblSuppApp.setForeground(new java.awt.Color(57, 62, 65));
        lblSuppApp.setText("Supplimentary Application Due Date");

        calInterview.setWeekOfYearVisible(false);

        lblInterview.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 16)); // NOI18N
        lblInterview.setForeground(new java.awt.Color(57, 62, 65));
        lblInterview.setText("Interview Due Date");

        cbxInterview.setBackground(new java.awt.Color(244, 243, 240));
        cbxInterview.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 16)); // NOI18N
        cbxInterview.setForeground(new java.awt.Color(57, 62, 65));
        cbxInterview.setText("Interview");
        cbxInterview.addActionListener(this::cbxInterviewActionPerformed);

        lblUniversityName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblUniversityName.setForeground(new java.awt.Color(57, 62, 65));
        lblUniversityName.setText("University Name");

        slbxUniversities.setBackground(new java.awt.Color(244, 243, 240));
        slbxUniversities.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 16)); // NOI18N

        btnCreate.setBackground(new java.awt.Color(88, 123, 127));
        btnCreate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(244, 243, 240));
        btnCreate.setText("Create");
        btnCreate.addActionListener(this::btnCreateActionPerformed);

        btnAddUni.setBackground(new java.awt.Color(88, 123, 127));
        btnAddUni.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnAddUni.setForeground(new java.awt.Color(244, 243, 240));
        btnAddUni.setText("+");
        btnAddUni.addActionListener(this::btnAddUniActionPerformed);

        javax.swing.GroupLayout pnlMainInterfaceLayout = new javax.swing.GroupLayout(pnlMainInterface);
        pnlMainInterface.setLayout(pnlMainInterfaceLayout);
        pnlMainInterfaceLayout.setHorizontalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainInterfaceLayout.createSequentialGroup()
                            .addComponent(btnCreate)
                            .addGap(301, 301, 301))
                        .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                            .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProgramName)
                                .addComponent(lblUniversityName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(48, 48, 48)
                            .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(slbxUniversities, 0, 360, Short.MAX_VALUE)
                                .addComponent(txfProgramName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAddUni)
                            .addGap(30, 30, 30)))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxInterview)
                            .addComponent(cbxSuppApp)
                            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblInterview))
                                    .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calSuppApp, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSuppApp)))))
                        .addContainerGap())))
        );
        pnlMainInterfaceLayout.setVerticalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversityName)
                    .addComponent(slbxUniversities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgramName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxSuppApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuppApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calSuppApp, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cbxInterview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInterview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        calSuppApp.setVisible(false);
        lblSuppApp.setVisible(false);
        calInterview.setVisible(false);
        lblInterview.setVisible(false);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(968, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxInterviewActionPerformed
        if (cbxInterview.isSelected()) {
            calInterview.setVisible(true);
            lblInterview.setVisible(true);
        } else {
            calInterview.setVisible(false);
            lblInterview.setVisible(false);
        }
    }//GEN-LAST:event_cbxInterviewActionPerformed

    private void cbxSuppAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSuppAppActionPerformed
        if (cbxSuppApp.isSelected()) {
            calSuppApp.setVisible(true);
            lblSuppApp.setVisible(true);
        } else {
            calSuppApp.setVisible(false);
            lblSuppApp.setVisible(false);
        }
    }//GEN-LAST:event_cbxSuppAppActionPerformed

    private void btnAddUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUniActionPerformed
        CreateUniversityGUI createUniversityGUI = new CreateUniversityGUI(currentUser);
        createUniversityGUI.setVisible(true);
        //Remove this screen
        this.dispose();
    }//GEN-LAST:event_btnAddUniActionPerformed

    
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String programName = ErrorCheck.trueStringParse(txfProgramName.getText(), 30, "Program Name", this);
        if (programName == null) {
            return;
        } else {
            for (University unis : currentUser.getTotalUniversitiesApplied()) {
                for (University.Application app : unis.getApplications()) {
                    if (unis.getUniversityName().equalsIgnoreCase(currentUser.getTotalUniversitiesApplied().get(slbxUniversities.getSelectedIndex()).getUniversityName()) && app.getProgramName().equalsIgnoreCase(programName)) {
                        JOptionPane.showMessageDialog(this, "Program Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } 
            }
        }
        boolean suppApp = cbxSuppApp.isSelected();
        LocalDate suppAppDate;
        if (suppApp) {
            int year = calSuppApp.getCalendar().get(Calendar.YEAR);
            int month = calSuppApp.getCalendar().get(Calendar.MONTH);
            int day = calSuppApp.getCalendar().get(Calendar.DAY_OF_MONTH);
            suppAppDate = LocalDate.of(year, month, day);
        } else {
            suppAppDate = null;
        }
        boolean interview = cbxInterview.isSelected();
        LocalDate interviewDate;
        if (interview) {
            int year = calInterview.getCalendar().get(Calendar.YEAR);
            int month = calInterview.getCalendar().get(Calendar.MONTH);
            int day = calInterview.getCalendar().get(Calendar.DAY_OF_MONTH);
            interviewDate = LocalDate.of(year, month, day);
        } else {
            interviewDate = null;
        }
        currentUser.getTotalUniversitiesApplied().get(slbxUniversities.getSelectedIndex()).genApplication(programName, suppApp, suppAppDate, interview, interviewDate, currentUser);
        
        //Create new screen
        UniversityApplicationsHomeScreenGUI universityApplicationsHomeScreenGUI = new UniversityApplicationsHomeScreenGUI(currentUser);
        universityApplicationsHomeScreenGUI.setVisible(true);
        //Remove this screen
        this.dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUni;
    private javax.swing.JButton btnCreate;
    private com.toedter.calendar.JCalendar calInterview;
    private com.toedter.calendar.JCalendar calSuppApp;
    private javax.swing.JCheckBox cbxInterview;
    private javax.swing.JCheckBox cbxSuppApp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblInterview;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblSuppApp;
    private javax.swing.JLabel lblUniversityName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private components.RoundedPanel pnlMainInterface;
    private javax.swing.JComboBox<String> slbxUniversities;
    private javax.swing.JTextField txfProgramName;
    // End of variables declaration//GEN-END:variables
}
