/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.Calendar;
import java.util.ArrayList;

/**
 *
 * @author louiske
 */
public class CreateApplicationGUI extends javax.swing.JFrame {
    private User currentUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UniversityApplicationsHomeScreenGUI.class.getName());

    /**
     * Creates new form UniversityApplicationsHomeScreenGUI
     */
    public CreateApplicationGUI() {
        this(null);
    }

    public CreateApplicationGUI(User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        for (University uni : currentUser.getTotalUniversitiesApplied()) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlMainInterface = new components.RoundedPanel();
        lblLoginUsername = new javax.swing.JLabel();
        slbxUniversities = new javax.swing.JComboBox<>();
        lblLoginUsername1 = new javax.swing.JLabel();
        txfLoginUsername = new javax.swing.JTextField();
        cbxSuppApp = new javax.swing.JCheckBox();
        calSuppAppDueDate = new com.toedter.calendar.JCalendar();
        lblSuppAppDueDate = new javax.swing.JLabel();
        calInterviewDueDate = new com.toedter.calendar.JCalendar();
        lblInterviewDueDate = new javax.swing.JLabel();
        cbxInterview = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFooter.setBackground(new java.awt.Color(244, 243, 240));

        lblFooter.setBackground(new java.awt.Color(244, 243, 240));
        lblFooter.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(57, 62, 65));
        lblFooter.setText("@ 2026 Global University Application Centre");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addGap(17, 17, 17))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addContainerGap())
        );

        pnlBackground.setBackground(new java.awt.Color(57, 62, 65));

        pnlMainInterface.setBackground(new java.awt.Color(244, 243, 240));

        lblLoginUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblLoginUsername.setForeground(new java.awt.Color(57, 62, 65));
        lblLoginUsername.setText("University:");

        slbxUniversities.setBackground(new java.awt.Color(244, 243, 240));
        slbxUniversities.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        slbxUniversities.setForeground(new java.awt.Color(57, 62, 65));

        lblLoginUsername1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblLoginUsername1.setForeground(new java.awt.Color(57, 62, 65));
        lblLoginUsername1.setText("Program Name:");

        txfLoginUsername.setBackground(new java.awt.Color(244, 243, 240));
        txfLoginUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        txfLoginUsername.setForeground(new java.awt.Color(57, 62, 65));

        cbxSuppApp.setBackground(new java.awt.Color(244, 243, 240));
        cbxSuppApp.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        cbxSuppApp.setForeground(new java.awt.Color(57, 62, 65));
        cbxSuppApp.setText("Supplimentary Application");
        cbxSuppApp.addActionListener(this::cbxSuppAppActionPerformed);

        calSuppAppDueDate.setBackground(new java.awt.Color(244, 243, 240));
        calSuppAppDueDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calSuppAppDueDate.setForeground(new java.awt.Color(57, 62, 65));
        calSuppAppDueDate.setDecorationBackgroundColor(new java.awt.Color(244, 243, 240));
        calSuppAppDueDate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        calSuppAppDueDate.setSundayForeground(new java.awt.Color(88, 123, 127));
        calSuppAppDueDate.setWeekOfYearVisible(false);
        calSuppAppDueDate.setWeekdayForeground(new java.awt.Color(88, 123, 127));

        lblSuppAppDueDate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblSuppAppDueDate.setForeground(new java.awt.Color(57, 62, 65));
        lblSuppAppDueDate.setText("Due Date");

        calInterviewDueDate.setBackground(new java.awt.Color(244, 243, 240));
        calInterviewDueDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calInterviewDueDate.setForeground(new java.awt.Color(57, 62, 65));
        calInterviewDueDate.setDecorationBackgroundColor(new java.awt.Color(244, 243, 240));
        calInterviewDueDate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        calInterviewDueDate.setSundayForeground(new java.awt.Color(88, 123, 127));
        calInterviewDueDate.setWeekOfYearVisible(false);
        calInterviewDueDate.setWeekdayForeground(new java.awt.Color(88, 123, 127));

        lblInterviewDueDate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblInterviewDueDate.setForeground(new java.awt.Color(57, 62, 65));
        lblInterviewDueDate.setText("Interview Date");

        cbxInterview.setBackground(new java.awt.Color(244, 243, 240));
        cbxInterview.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        cbxInterview.setForeground(new java.awt.Color(57, 62, 65));
        cbxInterview.setText("Interview");
        cbxInterview.addActionListener(this::cbxInterviewActionPerformed);

        javax.swing.GroupLayout pnlMainInterfaceLayout = new javax.swing.GroupLayout(pnlMainInterface);
        pnlMainInterface.setLayout(pnlMainInterfaceLayout);
        pnlMainInterfaceLayout.setHorizontalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxSuppApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginUsername)
                                    .addComponent(lblLoginUsername1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(slbxUniversities, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                    .addComponent(txfLoginUsername, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(132, 132, 132))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                                    .addComponent(cbxInterview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(66, 66, 66))
                                .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                                    .addComponent(lblInterviewDueDate)
                                    .addGap(29, 29, 29)
                                    .addComponent(calInterviewDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                                .addComponent(lblSuppAppDueDate)
                                .addGap(77, 77, 77)
                                .addComponent(calSuppAppDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        pnlMainInterfaceLayout.setVerticalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginUsername)
                    .addComponent(slbxUniversities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginUsername1)
                    .addComponent(txfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbxSuppApp)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(calSuppAppDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblSuppAppDueDate)))
                .addGap(18, 18, 18)
                .addComponent(cbxInterview)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(calInterviewDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblInterviewDueDate)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        calSuppAppDueDate.setVisible(false);
        lblSuppAppDueDate.setVisible(false);
        calInterviewDueDate.setVisible(false);
        lblInterviewDueDate.setVisible(false);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSuppAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSuppAppActionPerformed
        if (cbxSuppApp.isSelected()) {
            lblSuppAppDueDate.setVisible(true);
            calSuppAppDueDate.setVisible(true);
        } else {
            lblSuppAppDueDate.setVisible(false);
            calSuppAppDueDate.setVisible(false);
        }
    }//GEN-LAST:event_cbxSuppAppActionPerformed

    private void cbxInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxInterviewActionPerformed
        if (cbxInterview.isSelected()) {
            lblInterviewDueDate.setVisible(true);
            calInterviewDueDate.setVisible(true);
        } else {
            lblInterviewDueDate.setVisible(false);
            calInterviewDueDate.setVisible(false);
        }
    }//GEN-LAST:event_cbxInterviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UniversityApplicationsHomeScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar calInterviewDueDate;
    private com.toedter.calendar.JCalendar calSuppAppDueDate;
    private javax.swing.JCheckBox cbxInterview;
    private javax.swing.JCheckBox cbxSuppApp;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblInterviewDueDate;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblLoginUsername1;
    private javax.swing.JLabel lblSuppAppDueDate;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlFooter;
    private components.RoundedPanel pnlMainInterface;
    private javax.swing.JComboBox<String> slbxUniversities;
    private javax.swing.JTextField txfLoginUsername;
    // End of variables declaration//GEN-END:variables
}
