import javax.swing.JOptionPane;
import java.time.*;
import java.util.Calendar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdullahatif
 */
public class CreateUniversityGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreenGUI.class.getName());

    /**
     * Creates new form HomeScreenGUI
     */
    User currentUser;
    public CreateUniversityGUI() {
        initComponents();
        JOptionPane.showMessageDialog(this, "An Error Occured", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    public CreateUniversityGUI(User loggedInUser) {
        initComponents();
        currentUser = loggedInUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainInterface = new components.RoundedPanel();
        lblUniName = new javax.swing.JLabel();
        lblUniID = new javax.swing.JLabel();
        lblUniPassword = new javax.swing.JLabel();
        pnlCreateUniversity = new components.RoundedPanel();
        lblApplicationRedirect = new javax.swing.JLabel();
        txfUniName = new components.RoundedTextField();
        txfUniID = new components.RoundedTextField();
        txfUniPassword = new components.RoundedTextField();
        btnCreate = new components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(244, 243, 240));

        lblName.setBackground(new java.awt.Color(244, 243, 240));
        lblName.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(57, 62, 65));
        lblName.setText("GUAC");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBackground.setBackground(new java.awt.Color(57, 62, 65));

        pnlFooter.setBackground(new java.awt.Color(244, 243, 240));

        jLabel2.setBackground(new java.awt.Color(244, 243, 240));
        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 62, 65));
        jLabel2.setText("@ 2026 Global University Application Centre");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnlMainInterface.setBackground(new java.awt.Color(244, 243, 240));
        pnlMainInterface.setMinimumSize(new java.awt.Dimension(713, 755));

        lblUniName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblUniName.setForeground(new java.awt.Color(57, 62, 65));
        lblUniName.setText("University Name");

        lblUniID.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblUniID.setForeground(new java.awt.Color(57, 62, 65));
        lblUniID.setText("Login ID");

        lblUniPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblUniPassword.setForeground(new java.awt.Color(57, 62, 65));
        lblUniPassword.setText("Password");

        pnlCreateUniversity.setBackground(new java.awt.Color(88, 123, 127));

        lblApplicationRedirect.setBackground(new java.awt.Color(244, 243, 240));
        lblApplicationRedirect.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lblApplicationRedirect.setForeground(new java.awt.Color(244, 243, 240));
        lblApplicationRedirect.setText("Create University");

        javax.swing.GroupLayout pnlCreateUniversityLayout = new javax.swing.GroupLayout(pnlCreateUniversity);
        pnlCreateUniversity.setLayout(pnlCreateUniversityLayout);
        pnlCreateUniversityLayout.setHorizontalGroup(
            pnlCreateUniversityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateUniversityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblApplicationRedirect)
                .addGap(200, 200, 200))
        );
        pnlCreateUniversityLayout.setVerticalGroup(
            pnlCreateUniversityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateUniversityLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblApplicationRedirect)
                .addGap(17, 17, 17))
        );

        txfUniName.setBackground(new java.awt.Color(244, 243, 240));
        txfUniName.setBorder(null);
        txfUniName.setForeground(new java.awt.Color(57, 62, 65));
        txfUniName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUniName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N

        txfUniID.setBackground(new java.awt.Color(244, 243, 240));
        txfUniID.setBorder(null);
        txfUniID.setForeground(new java.awt.Color(57, 62, 65));
        txfUniID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUniID.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N

        txfUniPassword.setBackground(new java.awt.Color(244, 243, 240));
        txfUniPassword.setBorder(null);
        txfUniPassword.setForeground(new java.awt.Color(57, 62, 65));
        txfUniPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUniPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N

        btnCreate.setBorder(null);
        btnCreate.setForeground(new java.awt.Color(244, 243, 240));
        btnCreate.setText("Create");
        btnCreate.setToolTipText("");
        btnCreate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnCreate.addActionListener(this::btnCreateActionPerformed);

        javax.swing.GroupLayout pnlMainInterfaceLayout = new javax.swing.GroupLayout(pnlMainInterface);
        pnlMainInterface.setLayout(pnlMainInterfaceLayout);
        pnlMainInterfaceLayout.setHorizontalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreateUniversity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUniID)
                    .addComponent(lblUniPassword)
                    .addComponent(lblUniName))
                .addGap(54, 54, 54)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfUniID, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(txfUniPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfUniName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainInterfaceLayout.setVerticalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreateUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniName)
                    .addComponent(txfUniName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniID)
                    .addComponent(txfUniID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniPassword)
                    .addComponent(txfUniPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String uniName = ErrorCheck.trueStringParse(txfUniName.getText(), 40, "University Name", this);
        if (uniName == null) {
            return;
        } 
        if (University.isValidUniversity(uniName)) {
            JOptionPane.showMessageDialog(this, "University Not Located", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (University unis : currentUser.getTotalUniversitiesApplied()) {
            if (unis.getUniversityName().equalsIgnoreCase(uniName)) {
                JOptionPane.showMessageDialog(this, "University Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        String uniWebsite = University.getUniversityWebsite(uniName);
        String uniID = ErrorCheck.stringParse(txfUniID.getText(), 20, "University ID", this);
        String uniPassword = ErrorCheck.stringParse(txfUniPassword.getText(), 20, "University Password", this);
        currentUser.addTotalUniversitiesApplied(new University(uniName, uniWebsite, uniID, uniPassword));
        
        //Create new screen
        CreateApplicationGUI createApplicationGUI = new CreateApplicationGUI(currentUser);
        createApplicationGUI.setVisible(true);
        //Remove this screen
        this.dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedButton btnCreate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApplicationRedirect;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUniID;
    private javax.swing.JLabel lblUniName;
    private javax.swing.JLabel lblUniPassword;
    private javax.swing.JPanel pnlBackground;
    private components.RoundedPanel pnlCreateUniversity;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private components.RoundedPanel pnlMainInterface;
    private components.RoundedTextField txfUniID;
    private components.RoundedTextField txfUniName;
    private components.RoundedTextField txfUniPassword;
    // End of variables declaration//GEN-END:variables
}
