import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdullahatif
 */
public class HomeScreenGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreenGUI.class.getName());

    /**
     * Creates new form HomeScreenGUI
     */
    User currentUser;
    public HomeScreenGUI() {
        initComponents();
        JOptionPane.showMessageDialog(this, "An Error Occured", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    public HomeScreenGUI(User loggedInUser) {
        initComponents();
        currentUser = loggedInUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainInterface = new components.RoundedPanel();
        lblInstructions = new javax.swing.JLabel();
        pnlRedirect = new components.RoundedPanel();
        lblApplicationRedirect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(244, 243, 240));

        lblName.setBackground(new java.awt.Color(244, 243, 240));
        lblName.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(57, 62, 65));
        lblName.setText("GUAC");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBackground.setBackground(new java.awt.Color(57, 62, 65));

        pnlFooter.setBackground(new java.awt.Color(244, 243, 240));

        jLabel2.setBackground(new java.awt.Color(244, 243, 240));
        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 62, 65));
        jLabel2.setText("@ 2026 Global University Application Centre");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnlMainInterface.setBackground(new java.awt.Color(244, 243, 240));

        lblInstructions.setBackground(new java.awt.Color(244, 243, 240));
        lblInstructions.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lblInstructions.setForeground(new java.awt.Color(57, 62, 65));
        lblInstructions.setText("Continue to application");

        pnlRedirect.setBackground(new java.awt.Color(88, 123, 127));
        pnlRedirect.setForeground(new java.awt.Color(244, 243, 240));
        pnlRedirect.setToolTipText("");
        pnlRedirect.setCursor(new Cursor(Cursor.HAND_CURSOR));

        pnlRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRedirect.setBackground(new Color(57, 62, 65));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRedirect.setBackground(new Color(88, 123, 127));
            }
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (currentUser != null) {
                    new UniversityApplicationsHomeScreenGUI(currentUser).setVisible(true);
                } else {
                    new UniversityApplicationsHomeScreenGUI().setVisible(true);
                }
                dispose();
            }
        });

        lblApplicationRedirect.setBackground(new java.awt.Color(244, 243, 240));
        lblApplicationRedirect.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lblApplicationRedirect.setForeground(new java.awt.Color(244, 243, 240));
        lblApplicationRedirect.setText("University Application");
        lblApplicationRedirect.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblApplicationRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRedirect.dispatchEvent(evt);
            }
        });

        javax.swing.GroupLayout pnlRedirectLayout = new javax.swing.GroupLayout(pnlRedirect);
        pnlRedirect.setLayout(pnlRedirectLayout);
        pnlRedirectLayout.setHorizontalGroup(
            pnlRedirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedirectLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lblApplicationRedirect)
                .addGap(45, 45, 45))
        );
        pnlRedirectLayout.setVerticalGroup(
            pnlRedirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedirectLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblApplicationRedirect)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainInterfaceLayout = new javax.swing.GroupLayout(pnlMainInterface);
        pnlMainInterface.setLayout(pnlMainInterfaceLayout);
        pnlMainInterfaceLayout.setHorizontalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstructions)
                    .addComponent(pnlRedirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlMainInterfaceLayout.setVerticalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblInstructions)
                .addGap(18, 18, 18)
                .addComponent(pnlRedirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApplicationRedirect;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private components.RoundedPanel pnlMainInterface;
    private components.RoundedPanel pnlRedirect;
    // End of variables declaration//GEN-END:variables
}
