import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdullahatif
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        University.loadUniversities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jpnLogin = new javax.swing.JPanel();
        pnlMainInterface = new components.RoundedPanel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        lblLoginUsername = new javax.swing.JLabel();
        txfLoginUsername = new components.RoundedTextField();
        txfLoginPassword = new components.RoundedTextField();
        btnLogin = new components.RoundedButton();
        jpnSignUp = new javax.swing.JPanel();
        pnlSignUpMainInterface = new components.RoundedPanel();
        lblSignUpTitle = new javax.swing.JLabel();
        lblSignUpUsername = new javax.swing.JLabel();
        lblSignUpPassword = new javax.swing.JLabel();
        txfSignUpUsername = new components.RoundedTextField();
        txfSignUpPassword = new components.RoundedTextField();
        btnSignUp = new components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 62, 65));

        jTabbedPane.setToolTipText("");
        jTabbedPane.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        pnlMainInterface.setBackground(new java.awt.Color(244, 243, 240));

        lblLoginTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(57, 62, 65));
        lblLoginTitle.setText("Login");

        lblLoginPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblLoginPassword.setForeground(new java.awt.Color(57, 62, 65));
        lblLoginPassword.setText("Password");

        lblLoginUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblLoginUsername.setForeground(new java.awt.Color(57, 62, 65));
        lblLoginUsername.setText("Username");

        txfLoginUsername.setBackground(new java.awt.Color(244, 243, 240));
        txfLoginUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        txfLoginUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfLoginUsernameKeyPressed(evt);
            }
        });

        txfLoginPassword.setBackground(new java.awt.Color(244, 243, 240));
        txfLoginPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N

        btnLogin.setBackground(new java.awt.Color(88, 123, 127));
        btnLogin.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(244, 243, 240));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout pnlMainInterfaceLayout = new javax.swing.GroupLayout(pnlMainInterface);
        pnlMainInterface.setLayout(pnlMainInterfaceLayout);
        pnlMainInterfaceLayout.setHorizontalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginPassword)
                            .addComponent(lblLoginUsername))
                        .addGap(113, 113, 113)
                        .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lblLoginTitle))
                    .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnlMainInterfaceLayout.setVerticalGroup(
            pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInterfaceLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLoginTitle)
                .addGap(34, 34, 34)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginUsername)
                    .addComponent(txfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginPassword)
                    .addComponent(txfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        lblLoginPassword.setVisible(false);
        txfLoginPassword.setVisible(false);

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Login", jpnLogin);

        pnlSignUpMainInterface.setBackground(new java.awt.Color(244, 243, 240));

        lblSignUpTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        lblSignUpTitle.setForeground(new java.awt.Color(60, 63, 65));
        lblSignUpTitle.setText("Sign Up");

        lblSignUpUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblSignUpUsername.setForeground(new java.awt.Color(60, 63, 65));
        lblSignUpUsername.setText("Username");

        lblSignUpPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lblSignUpPassword.setForeground(new java.awt.Color(60, 63, 65));
        lblSignUpPassword.setText("Password");

        txfSignUpUsername.setBackground(new java.awt.Color(244, 243, 240));
        txfSignUpUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N

        txfSignUpPassword.setBackground(new java.awt.Color(244, 243, 240));
        txfSignUpPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N

        btnSignUp.setBackground(new java.awt.Color(88, 123, 127));
        btnSignUp.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(244, 243, 240));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);

        javax.swing.GroupLayout pnlSignUpMainInterfaceLayout = new javax.swing.GroupLayout(pnlSignUpMainInterface);
        pnlSignUpMainInterface.setLayout(pnlSignUpMainInterfaceLayout);
        pnlSignUpMainInterfaceLayout.setHorizontalGroup(
            pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpMainInterfaceLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignUpUsername)
                    .addComponent(lblSignUpPassword))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfSignUpPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSignUpUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addGroup(pnlSignUpMainInterfaceLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignUpTitle)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pnlSignUpMainInterfaceLayout.setVerticalGroup(
            pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpMainInterfaceLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSignUpTitle)
                .addGap(34, 34, 34)
                .addGroup(pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpMainInterfaceLayout.createSequentialGroup()
                        .addComponent(txfSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlSignUpMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSignUpPassword)))
                    .addComponent(lblSignUpUsername))
                .addGap(32, 32, 32)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnSignUpLayout = new javax.swing.GroupLayout(jpnSignUp);
        jpnSignUp.setLayout(jpnSignUpLayout);
        jpnSignUpLayout.setHorizontalGroup(
            jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSignUpLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlSignUpMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpnSignUpLayout.setVerticalGroup(
            jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSignUpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlSignUpMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Sign Up", jpnSignUp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean loginPassword = false;
    private String usernameLogin;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (loginPassword) {
            String passwordInput = ErrorCheck.stringParse(txfLoginPassword.getText(), 10, "Password", this);
            if (passwordInput == null) {
                return;
            }
            User loggedInUser = User.login(usernameLogin, passwordInput, this);
            if (loggedInUser == null) {
                return;
            } else {
                //Create new remove employees screen
                loggedInUser.readUserUniversities();
                UniversityApplicationsHomeScreenGUI homeScreenGUI = new UniversityApplicationsHomeScreenGUI(loggedInUser);
                homeScreenGUI.setVisible(true);
                //Remove this screen
                this.dispose();
            }
        } else {
            String usernameInput = ErrorCheck.trueStringParse(txfLoginUsername.getText(), 10, "Username", this);
            if (usernameInput == null) {
                return;
            } else if (User.checkUserExists(usernameInput, this)) {
                loginPassword = true;
                lblLoginPassword.setVisible(true);
                txfLoginPassword.setVisible(true);
                usernameLogin = usernameInput;
            } else {
                JOptionPane.showMessageDialog(this, "User Not Found", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txfLoginUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfLoginUsernameKeyPressed
        if (loginPassword) {
            txfLoginPassword.setText("");
            lblLoginPassword.setVisible(false);
            txfLoginPassword.setVisible(false);
            loginPassword = false;
        }
    }//GEN-LAST:event_txfLoginUsernameKeyPressed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String usernameInput = ErrorCheck.trueStringParse(txfSignUpUsername.getText(), 10, "Username", this);
        if (usernameInput == null) {
            return;
        }
        String passwordInput = ErrorCheck.stringParse(txfSignUpPassword.getText(), 10, "Password", this);
        if (passwordInput == null) {
            return;
        }   
        User.signUp(usernameInput, passwordInput, this);
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnSignUp;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpTitle;
    private javax.swing.JLabel lblSignUpUsername;
    private javax.swing.JPanel pnlMainInterface;
    private javax.swing.JPanel pnlSignUpMainInterface;
    private javax.swing.JTextField txfLoginPassword;
    private javax.swing.JTextField txfLoginUsername;
    private javax.swing.JTextField txfSignUpPassword;
    private javax.swing.JTextField txfSignUpUsername;
    // End of variables declaration//GEN-END:variables
}
