import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdullahatif
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jpnLogin = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        txfLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txfLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jpnSignUp = new javax.swing.JPanel();
        lblSignUpTitle = new javax.swing.JLabel();
        txfSignUpUsername = new javax.swing.JTextField();
        lblSignUpUsername = new javax.swing.JLabel();
        txfSignUpPassword = new javax.swing.JTextField();
        lblSignUpPassword = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setToolTipText("");

        lblLoginTitle.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        lblLoginTitle.setText("Login");

        txfLoginUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfLoginUsernameKeyPressed(evt);
            }
        });

        lblLoginUsername.setText("Username");

        lblLoginPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLogin)
                    .addComponent(lblLoginTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnLoginLayout.createSequentialGroup()
                        .addComponent(lblLoginPassword)
                        .addGap(1, 1, 1))
                    .addComponent(lblLoginUsername))
                .addGap(129, 129, 129)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblLoginTitle)
                .addGap(32, 32, 32)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginPassword))
                .addGap(48, 48, 48)
                .addComponent(btnLogin)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        txfLoginPassword.setVisible(false);
        lblLoginPassword.setVisible(false);

        jTabbedPane.addTab("Login", jpnLogin);

        lblSignUpTitle.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        lblSignUpTitle.setText("Sign Up!");

        lblSignUpUsername.setText("Username");

        lblSignUpPassword.setText("Password");

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);

        javax.swing.GroupLayout jpnSignUpLayout = new javax.swing.GroupLayout(jpnSignUp);
        jpnSignUp.setLayout(jpnSignUpLayout);
        jpnSignUpLayout.setHorizontalGroup(
            jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSignUpLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSignUp)
                    .addComponent(lblSignUpTitle))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSignUpLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnSignUpLayout.createSequentialGroup()
                        .addComponent(lblSignUpPassword)
                        .addGap(1, 1, 1))
                    .addComponent(lblSignUpUsername))
                .addGap(129, 129, 129)
                .addGroup(jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        jpnSignUpLayout.setVerticalGroup(
            jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSignUpLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblSignUpTitle)
                .addGap(32, 32, 32)
                .addGroup(jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignUpUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignUpPassword))
                .addGap(48, 48, 48)
                .addComponent(btnSignUp)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Sign Up", jpnSignUp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean loginPassword = false;
    private String usernameLogin;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (loginPassword) {
            String passwordInput = ErrorCheck.stringParse(txfLoginPassword.getText(), 10, "Password", this);
            if (passwordInput == null) {
                return;
            }
            User loggedInUser = User.login(usernameLogin, passwordInput, this);
            if (loggedInUser == null) {
                return;
            } else {
                //Create new remove employees screen
                HomeScreenGUI homeScreenGUI = new HomeScreenGUI(loggedInUser);
                homeScreenGUI.setVisible(true);
                //Remove this screen
                this.dispose();
            }
        } else {
            String usernameInput = ErrorCheck.trueStringParse(txfLoginUsername.getText(), 10, "Username", this);
            if (usernameInput == null) {
                return;
            } else if (User.checkUserExists(usernameInput, this)) {
                loginPassword = true;
                lblLoginPassword.setVisible(true);
                txfLoginPassword.setVisible(true);
                usernameLogin = usernameInput;
            } else {
                JOptionPane.showMessageDialog(this, "User Not Found", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txfLoginUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfLoginUsernameKeyPressed
        if (loginPassword) {
            txfLoginPassword.setText("");
            lblLoginPassword.setVisible(false);
            txfLoginPassword.setVisible(false);
            loginPassword = false;
        }
    }//GEN-LAST:event_txfLoginUsernameKeyPressed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String usernameInput = ErrorCheck.trueStringParse(txfSignUpUsername.getText(), 10, "Username", this);
        if (usernameInput == null) {
            return;
        }
        String passwordInput = ErrorCheck.stringParse(txfSignUpPassword.getText(), 10, "Password", this);
        if (passwordInput == null) {
            return;
        }
        User.signUp(usernameInput, passwordInput, this);
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnSignUp;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpTitle;
    private javax.swing.JLabel lblSignUpUsername;
    private javax.swing.JTextField txfLoginPassword;
    private javax.swing.JTextField txfLoginUsername;
    private javax.swing.JTextField txfSignUpPassword;
    private javax.swing.JTextField txfSignUpUsername;
    // End of variables declaration//GEN-END:variables
}
